Life Science Login provider
SocialiteProviders/Providers pull request #1010
Opened 2023-04-24 14:25 UTC by mzur

This adds a new provider for [Life Science Login](https://lifescience-ri.eu/ls-login/) (from the European life science infrastructure).

2023-04-29 00:32 UTC, atymic commented on src/LifeScienceLogin/README.md
> +return Socialite::driver('lifesciencelogin')->redirect();
Add returned fields please

2023-04-29 00:32 UTC, atymic commented on src/LifeScienceLogin/Provider.php
> +class Provider extends AbstractProvider
Can we get an `@see` for the docs URL

2023-04-29 00:33 UTC, atymic requested changes

2023-04-29 00:33 UTC, atymic commented on src/LifeScienceLogin/composer.json
> +        "php": "^7.4 || ^8.0",
Drop 7.x

2023-04-30 00:58 UTC, atymic approved these changes

2023-04-30 00:59 UTC, merged

2023-05-01 12:11 UTC, mzur commented
Thanks! I'll also create a PR for the website. Do I have to do anything for the package to be published to Packagist?

2023-05-01 12:32 UTC, atymic commented
Oops, forgot. Done :)