feat: add Ministry Platform provider
SocialiteProviders/Providers pull request #1050
Opened 2023-08-07 16:41 UTC by Cdrew92

https://kb.ministryplatform.com/kb/develop/oauth-2-0

2023-08-31 09:54 UTC, lucasmichot requested changes
Some changes requested

2023-08-31 09:54 UTC, lucasmichot commented on src/MinistryPlatform/Provider.php
> +    protected function getTokenFields($code)
Can you remove this method ?

2023-08-31 09:54 UTC, lucasmichot commented on src/MinistryPlatform/Provider.php
> +            'headers' => [
```suggestion
            \GuzzleHttp\RequestOptions::HEADERS => [
```

2023-08-31 09:54 UTC, lucasmichot commented on src/MinistryPlatform/Provider.php
> +     * {@inheritdoc}
Please add a proper docblock here,`{@inheritdoc}` is only if there is already a parent method

2023-08-31 09:54 UTC, lucasmichot commented on src/MinistryPlatform/Provider.php
> +    protected function getMPUrl()
Can you rename this method to `baseUrl` instead?

2023-08-31 09:54 UTC, lucasmichot commented on src/MinistryPlatform/Provider.php
> +        return json_decode($response->getBody(), true);
```suggestion
        return json_decode((string) $response->getBody(), true);
```

2023-08-31 09:54 UTC, lucasmichot commented on src/MinistryPlatform/README.md
> +        'SocialiteProviders\\MinistryPlatform\\MinistryPlatformExtendSocialite@handle',
```suggestion
        \SocialiteProviders\MinistryPlatform\MinistryPlatformExtendSocialite::class.'@handle',
```

2023-08-31 09:54 UTC, lucasmichot commented on src/MinistryPlatform/composer.json
> +        "php": "^7.3|^8.0",
```suggestion
        "php": "^8.0",
```

2023-08-31 09:54 UTC, lucasmichot commented on src/MinistryPlatform/composer.json
> +        "socialiteproviders/manager": "^4.1"
```suggestion
        "socialiteproviders/manager": "^4.4"
```

2023-08-31 09:54 UTC, lucasmichot commented on src/MinistryPlatform/Provider.php
> +    // /**
Can you remove `//` ?

2023-09-25 21:46 UTC, Cdrew92 commented
@lucasmichot - Issues are resolved!

2024-02-07 12:54 UTC, closed without merging