Added force HTTPS config option for Steam provider
SocialiteProviders/Providers pull request #1066
Opened 2023-08-23 19:14 UTC by fkrzski

I added this option because of my problem today - I deployed my application to production using a Docker container (I don't use HTTPS in the container, it's just a reverse proxy from HTTPS to the container) and I can't log in via Steam. I found the problem, solved it and created a pull request

2023-08-24 07:46 UTC, lucasmichot requested changes

2023-08-24 07:46 UTC, lucasmichot commented on src/Steam/Provider.php
> +        $response = $this->getHttpClient()->request('POST', self::OPENID_URL, $requestOptions);
Please revert this change.

2023-08-24 07:46 UTC, lucasmichot commented on src/Steam/Provider.php
> +        $response = $this->getHttpClient()->request(
Can you revert this change?

2023-08-24 07:46 UTC, lucasmichot commented on src/Steam/README.md
> +  'force_https' => true,  // This will be force HTTPS scheme
```suggestion
  'force_https' => true,  // This will force HTTPS scheme
```

2023-08-24 07:46 UTC, lucasmichot commented on src/Steam/README.md
> +If you do not set it scheme will be got from your server settings
```suggestion
If you do not set it, the scheme will be inferred from your server settings
```

2023-08-24 14:33 UTC, fkrzski commented on src/Steam/Provider.php
> +        $response = $this->getHttpClient()->request(
Yeah

2023-08-24 14:33 UTC, fkrzski commented on src/Steam/Provider.php
> +        $response = $this->getHttpClient()->request('POST', self::OPENID_URL, $requestOptions);
Yeah

2023-08-24 14:36 UTC, lucasmichot approved these changes
GTM @atymic

2023-08-28 01:16 UTC, atymic approved these changes

2023-08-28 01:16 UTC, merged