Added support to read sp_sign_assertions key to remove hardcoded value
SocialiteProviders/Providers pull request #1107
Opened 2023-11-01 15:25 UTC by bruno-farias

Replaced hard-coded value, now it's reading the sp_sign_assertions from the config key and setting the given value, default to true to avoid breaking changes.

2023-11-02 02:47 UTC, atymic commented
@27pchrisl

2023-11-02 12:01 UTC, 27pchrisl commented
@atymic Looks good to me, thanks @bruno-farias !

2023-11-06 09:31 UTC, lucasmichot requested changes

2023-11-06 09:31 UTC, lucasmichot commented on src/Saml2/Provider.php
> +            ->setWantAssertionsSigned($this->getConfig('sp_sign_assertions', true))
```suggestion
            ->setWantAssertionsSigned((bool) $this->getConfig('sp_sign_assertions', true))
```

2023-11-06 09:53 UTC, bruno-farias commented
@lucasmichot updated, thanks for the input.

2023-11-07 22:06 UTC, atymic approved these changes

2023-11-07 22:07 UTC, merged