fix(okta): remove duplicate credentials
SocialiteProviders/Providers pull request #1150
Opened 2024-02-15 01:44 UTC by Tugzrida

https://github.com/laravel/socialite/pull/684 added the client_id and client_secret to the Authorization header in addition to the request body, however Okta throws an error if multiple credentials are provided, so they must be removed from the body before sending the request.

2024-02-15 12:24 UTC, lucasmichot requested changes
Some minor changes requested

2024-02-15 12:24 UTC, lucasmichot commented on src/Okta/Provider.php
> +        // Okta doesn't like credentials being provided in both the Authorization header and body
```suggestion
        // Okta does not support credentials being provided in both the Authorization header and body.
```

2024-02-15 12:24 UTC, lucasmichot commented on src/Okta/Provider.php
> +        unset($fields['client_id']);
Or just `unset($fields['client_id'], $fields['client_secret']);`

2024-02-15 22:19 UTC, lucasmichot approved these changes

2024-02-16 09:00 UTC, driesvints commented
I've reverted the original PR. Thanks!

2024-02-16 09:01 UTC, lucasmichot commented
> I've reverted the original PR.

Thanks for the head up @driesvints - I'll have a look at that

2024-02-16 09:49 UTC, Tugzrida commented
Closing as https://github.com/laravel/socialite/pull/694 reverts the introduction of the bug

2024-02-16 09:49 UTC, closed without merging