Add refreshToken for HubSpot
SocialiteProviders/Providers pull request #1167
Opened 2024-03-04 14:07 UTC by dansleboby

Add refreshToken method for Hubspot

Inspire by:
https://github.com/SocialiteProviders/Apple/blob/master/Provider.php#L289-L299

2024-03-13 13:13 UTC, lucasmichot requested changes
Can you return an array instead

2024-03-13 13:13 UTC, lucasmichot commented on src/HubSpot/Provider.php
> +        return $this->getHttpClient()->post($this->getTokenUrl(), [
```suggestion
        $response = $this->getHttpClient()->post($this->getTokenUrl(), [
```

2024-03-13 13:13 UTC, lucasmichot commented on src/HubSpot/Provider.php
> +     * @return ResponseInterface
```suggestion
     * @return array
```

2024-03-13 13:13 UTC, lucasmichot commented on src/HubSpot/Provider.php
> +        ]);
```suggestion
        ]);
        
        return json_decode((string) $response->getBody(), true);
```

2024-03-13 13:53 UTC, dansleboby commented
Yes, but we should change Apple too to keep a standard

2024-06-08 23:52 UTC, atymic approved these changes

2024-06-08 23:52 UTC, merged