Add support for optional post_logout_redirect_uri
SocialiteProviders/Providers pull request #1174
Opened 2024-03-13 07:45 UTC by Tamas-hi

Fixes #1173

2024-03-13 13:10 UTC, lucasmichot requested changes

2024-03-13 13:10 UTC, lucasmichot commented on src/Azure/Provider.php
> +        $queryParams = [];
Why not just :

```php
$logoutUrl = $this->getBaseUrl().'/oauth2/logout';

return $redirectUri === null ?
    $logoutUrl :
    $logoutUrl.'?'.http_build_query(['post_logout_redirect_uri' => $redirectUri], '', '&', $this->encodingType);
```

2024-03-13 16:41 UTC, Tamas-hi commented on src/Azure/Provider.php
> +        $queryParams = [];
Yes, we can do that. I'll adjusted it

2024-03-15 01:58 UTC, atymic approved these changes

2024-03-15 03:02 UTC, merged