Make TikTok username optional based on scopes set
SocialiteProviders/Providers pull request #1183
Opened 2024-03-28 13:30 UTC by Skullbock

In v2, `username` can be requested only if `user.info.profile` scope is set.
Instead of forcing the scope, since it's not even in the default list of scopes set in the provider, we could just add the username field if the scope is present.

2024-03-29 08:38 UTC, lucasmichot approved these changes

2024-04-01 01:29 UTC, atymic requested changes
See comment

2024-04-01 01:29 UTC, atymic commented on src/TikTok/Provider.php
> +        if (in_array('user.info.profile', $fields)) {
Hmm should this not be checking scopes, not `$fields` ?

2024-04-29 01:38 UTC, merged

2024-06-10 16:13 UTC, liamseys commented
I got approved and added this scope, but I still can't see the username.

2024-06-11 09:39 UTC, liamseys commented
@atymic I debugged this: the username field isn't being passed to the fields list when the scope was added. Was this tested before merging?

2024-06-11 22:00 UTC, atymic commented
@liamseys can you share the scopes you're using in laravel?

2024-06-12 14:13 UTC, liamseys commented
@atymic

```
return Socialite::driver('tiktok')
            ->scopes(['user.info.basic', 'user.info.profile'])
            ->redirect();
```

2024-06-12 14:14 UTC, liamseys commented
<img width="1070" alt="Scherm­afbeelding 2024-06-12 om 16 13 49" src="https://github.com/SocialiteProviders/Providers/assets/10025985/d43cd559-8999-41c6-a217-5174d0c1b711">

2024-06-12 18:16 UTC, liamseys commented
```
array:1 [▼ // vendor/socialiteproviders/tiktok/Provider.php:107
  0 => "user.info.basic"
]
```

When I print ```$this->scopes``` in the Provider.php file, I only see user.info.basic, even though I set more in the scopes method.

2024-06-12 22:40 UTC, atymic commented
It should merge them correctly
![Screen Shot 2024-06-13 at 08 38 25](https://github.com/SocialiteProviders/Providers/assets/50683531/5c758f25-d9b3-4155-b4a5-a2e92e3df6ce)

Can you show your whole controller? Do you set the scopes also when you call `->user();`