Add Roblox OAuth2 Provider for Laravel Socialite
SocialiteProviders/Providers pull request #1192
Opened 2024-04-12 15:22 UTC by sympact06

This commit introduces the Roblox OAuth2 Provider for Laravel Socialite. It includes the provider's installation and usage instructions in the README file as well as the implementation of the Provider class. It also updates the monorepo-builder.yml file to include a new reference to the Roblox provider repository.

2024-04-16 02:10 UTC, atymic requested changes

2024-04-16 02:10 UTC, atymic commented on src/Roblox/Provider.php
> +    public static function additionalConfigKeys()
Can leave this out

2024-04-16 02:10 UTC, atymic commented on src/Roblox/composer.json
> +    "name": "socialiteproviders/discord",
this is wrong

2024-04-16 09:53 UTC, sympact06 commented on src/Roblox/Provider.php
> +    public static function additionalConfigKeys()
Fixed

2024-04-16 09:53 UTC, sympact06 commented
Fixed the comments

2024-04-16 11:48 UTC, lucasmichot commented on src/Roblox/Provider.php
> +            'client_id' => $this->clientId,
Aren't these properties already set in the parent method?

2024-06-08 23:51 UTC, atymic approved these changes

2024-06-08 23:51 UTC, merged

2024-06-09 01:43 UTC, atymic commented
Please PR to website https://github.com/SocialiteProviders/website