fix: threads profile picture url if not available and update readme
SocialiteProviders/Providers pull request #1247
Opened 2024-08-20 12:50 UTC by Akmalfauzi

2024-08-20 23:18 UTC, atymic commented
I don't see any changes here. Arr::get already returns null?

2024-08-21 01:04 UTC, Akmalfauzi commented
Yes, that's right, because in my case, it only returns the id and username fields.

So, I fixed the undefined index "threads_profile_picture_url" error so that it could still run even though the "threads_profile_picture_url" field did not exist or was empty.

2024-08-21 01:09 UTC, Akmalfauzi commented
I also fixed the typo in the `README.md` file when adding code to the `EventServiceProvider.php` file

<img width="1133" alt="Screenshot 2024-08-21 at 08 06 42" src="https://github.com/user-attachments/assets/d8f1b0ea-3b3f-4df3-a4af-f78e748cb0c4">

2024-08-21 01:11 UTC, atymic commented
`Arr::get` will return null already if the field does not exist?

2024-08-21 01:15 UTC, Akmalfauzi commented
Yes, that's right.

2024-08-22 04:27 UTC, atymic requested changes
Just this change then it's good merge.

2024-08-22 04:27 UTC, atymic commented on src/Threads/Provider.php
> +            'avatar'       => Arr::get($user, 'threads_profile_picture_url') ?? null,
```suggestion
            'avatar'       => Arr::get($user, 'threads_profile_picture_url'),
```

No need to add the null coalesce

2024-08-22 09:54 UTC, Akmalfauzi commented on src/Threads/Provider.php
> +            'avatar'       => Arr::get($user, 'threads_profile_picture_url') ?? null,
hmm, oke thank you. i will fix soon.

2024-08-22 21:28 UTC, atymic approved these changes

2024-08-22 21:29 UTC, merged