Add Calendly as a Provider
SocialiteProviders/Providers pull request #1265
Opened 2024-10-04 19:58 UTC by paulchrisluke

This PR is adds [Calendly](https://calendly.com/) Provider

[Official Calendly API Docs](https://developer.calendly.com/getting-started)
[CalendlyPartners Portal](https://developer.calendly.com/create-a-developer-account)

2024-10-05 05:19 UTC, atymic commented on src/Calendly/README.md
> +- ``email``
Can you add the additional fields here please?

2024-10-05 05:19 UTC, atymic requested changes
One small change

2024-10-05 05:19 UTC, atymic commented on src/Calendly/composer.json
> +        "php": "^8.0",
```suggestion
        "php": "^8.1",
```

2024-10-05 14:32 UTC, paulchrisluke commented
Thank you @atymic , got that changed 👍🏽

2024-10-18 01:12 UTC, atymic approved these changes

2024-10-18 01:12 UTC, merged