Add Infomaniak provider
SocialiteProviders/Providers pull request #1296
Opened 2024-11-15 15:18 UTC by L3o-pold

2024-11-17 09:26 UTC, lucasmichot requested changes
Thanks for the PR Léopold, some changes requested

2024-11-17 09:26 UTC, lucasmichot commented on src/Infomaniak/InfomaniakExtendSocialite.php
> +    public function handle(SocialiteWasCalled $socialiteWasCalled)
```suggestion
    public function handle(SocialiteWasCalled $socialiteWasCalled): void
```

2024-11-17 09:26 UTC, lucasmichot commented on src/Infomaniak/Provider.php
> +     * {@inheritdoc}
You can drop this docblock

2024-11-17 09:26 UTC, lucasmichot commented on src/Infomaniak/Provider.php
> +     * {@inheritdoc}
Same here

2024-11-17 09:26 UTC, lucasmichot commented on src/Infomaniak/Provider.php
> +     * {@inheritdoc}
Same here

2024-11-17 09:26 UTC, lucasmichot commented on src/Infomaniak/Provider.php
> +     * {@inheritdoc}
Same here

2024-11-17 09:26 UTC, lucasmichot commented on src/Infomaniak/composer.json
> +{
Can you also add the `keywords` and `support` section?

2024-11-17 09:45 UTC, L3o-pold commented
I used https://github.com/SocialiteProviders/Generators so maybe we needs to change it too.

2024-11-17 14:47 UTC, lucasmichot approved these changes
GTM @atymic

2024-11-17 14:52 UTC, lucasmichot commented
@L3o-pold , can you make also a PR on https://github.com/SocialiteProviders/website ?

2024-11-18 13:26 UTC, L3o-pold commented
done: https://github.com/SocialiteProviders/website/pull/68

2024-11-20 05:42 UTC, atymic approved these changes

2024-11-20 05:42 UTC, merged