feat: add klarna provider
SocialiteProviders/Providers pull request #1297
Opened 2024-11-15 15:48 UTC by taher435

Add Klarna login provider

2024-11-17 09:31 UTC, lucasmichot requested changes
Thanks for the PR, can you also add an entry to https://github.com/SocialiteProviders/Providers/blob/master/monorepo-builder.yml ?

2024-11-17 09:31 UTC, lucasmichot commented on src/Klarna/README.md
> +  'client_id' => env('CLIENT_ID'),
```suggestion
  'client_id' => env('KLARNA_CLIENT_ID'),
```

2024-11-17 09:31 UTC, lucasmichot commented on src/Klarna/README.md
> +  'client_secret' => env('CLIENT_SECRET'),
```suggestion
  'client_secret' => env('KLARNA_CLIENT_SECRET'),
```

2024-11-17 14:51 UTC, lucasmichot approved these changes
GTM @atymic

2024-11-17 14:51 UTC, lucasmichot commented
@taher435 , can you make also a PR on https://github.com/SocialiteProviders/website ?

2024-11-18 13:32 UTC, taher435 commented
> @taher435 , can you make also a PR on https://github.com/SocialiteProviders/website ?

@lucasmichot done. https://github.com/SocialiteProviders/website/pull/69

2024-11-20 10:01 UTC, taher435 commented
> GTM @atymic

Hey @atymic are you able to review this PR? Thank you 🙏

2024-11-20 10:10 UTC, lucasmichot approved these changes
Reviewed again after

2024-11-23 11:23 UTC, merged