added gitea provider
SocialiteProviders/Providers pull request #365
Opened 2019-11-12 11:16 UTC by ederuiter

This adds support for gitea (https://gitea.io). The code is largely copy/pasted from the gitlab provider, but with some minor changes (different url's + other fields returned from the user api)

2020-04-28 10:36 UTC, atymic commented
@ederuiter 
Please PR docs. Will close in one 1 week if no activity.

2020-05-06 04:22 UTC, atymic commented
Closing due to inactivity. Please ping me if you'd like to get this merged and I will repopen.

2020-08-26 15:35 UTC, ederuiter commented
@atymic I have created PR for the website https://github.com/SocialiteProviders/website/pull/9 
Is this sufficient or do you need more?

PS: https://socialiteproviders.com/contribute/#creating-a-provider does not mention the docs PR

2020-08-26 23:40 UTC, atymic requested changes

2020-08-26 23:40 UTC, atymic commented on src/Gitea/composer.json
> +        "socialiteproviders/manager": "~2.0 || ~3.0"
drop v2 here please

2020-08-26 23:40 UTC, atymic commented on src/Gitea/composer.json
> +        "php": "^5.6 || ^7.0",
drop < 7.2 please

2020-08-26 23:41 UTC, atymic commented
@ederuiter 
To generate the docs (now live in this repo) run the `doc-gen.php` script in the tools folder 👍

2020-08-27 08:41 UTC, merged