Add SuperOffice provider
SocialiteProviders/Providers pull request #586
Opened 2020-11-18 10:20 UTC by SuperDJ

2020-11-18 20:12 UTC, atymic requested changes
Looks good, just some minor stuff.

2020-11-18 20:12 UTC, atymic commented on src/SuperOffice/Provider.php
> +			'https://'.$this->config['environment'].'.superoffice.com/'.$this->config['customer_id'].'/api/v1/User/currentPrincipal',
could we use sprintf here instead please?

2020-11-18 20:12 UTC, atymic commented on src/SuperOffice/Provider.php
> +		return 'https://'.($this->config['environment'] ?: 'sod').'.superoffice.com/login/common/oauth/tokens';
Also sprintf here would be a little cleaner (and above)

2020-11-18 20:12 UTC, atymic commented on src/SuperOffice/Provider.php
> +}
Missing newline at the end of the file

2020-11-18 20:12 UTC, atymic commented on src/SuperOffice/README.md
> +composer require socialiteproviders/microsoft
need to change this

2020-11-18 20:12 UTC, atymic commented on src/SuperOffice/README.md
> +# Microsoft
And this

2020-11-18 20:12 UTC, atymic commented on src/SuperOffice/README.md
> +```
Could you add a list of returned user fields and link to the docs?

Ex: https://socialiteproviders.com/Kakao/#returned-user-fields

2020-11-18 20:12 UTC, atymic commented on src/SuperOffice/composer.json
> +}
newline

2020-11-24 07:33 UTC, SuperDJ commented
@atymic what can be done to speed up the merge process?

2020-11-24 07:34 UTC, atymic commented
Sorry, didn't see your last commit. Can you fix the styleci issues, then i'll merge? Thanks!

2020-11-24 07:55 UTC, SuperDJ commented
@atymic that should do

2020-11-24 21:24 UTC, atymic approved these changes

2020-11-24 21:25 UTC, merged