Add MusicBrainz Provider
SocialiteProviders/Providers pull request #768
Opened 2021-11-08 20:06 UTC by andrzejkupczyk

2021-11-11 09:22 UTC, lucasmichot requested changes
Thanks for the PR @andrzejkupczyk 
Can you adjust the PR with the review comments ?

2021-11-11 09:22 UTC, lucasmichot commented on src/MusicBrainz/MusicBrainzExtendSocialite.php
> +     */
Missing `@param` declaration here

2021-11-11 09:22 UTC, lucasmichot commented on src/MusicBrainz/Provider.php
> +    protected $scopes = ['profile'];
Missing `@inheritdoc` declaration here

2021-11-11 09:22 UTC, lucasmichot commented on src/MusicBrainz/Provider.php
> +    protected $scopeSeparator = ' ';
same here

2021-11-11 09:22 UTC, lucasmichot commented on src/MusicBrainz/Provider.php
> +    protected $usesPKCE = true;
same here

2021-11-11 09:22 UTC, lucasmichot commented on src/MusicBrainz/Provider.php
> +    protected function getTokenFields($code)
This method can be removed

2021-11-11 09:22 UTC, lucasmichot commented on src/MusicBrainz/README.md
> +        'SocialiteProviders\\MusicBrainz\\MusicBrainzExtendSocialite@handle',
```suggestion
        \SocialiteProviders\MusicBrainz\MusicBrainzExtendSocialite::class.'@handle',
```

2021-11-11 10:37 UTC, lucasmichot approved these changes
Thanks for this PR @andrzejkupczyk 
GTM @atymic 👍

2021-11-11 10:39 UTC, andrzejkupczyk commented
Thanks for the review, @lucasmichot 👍🏻

2021-12-13 00:31 UTC, atymic approved these changes

2021-12-13 00:31 UTC, merged