Add Monday provider
SocialiteProviders/Providers pull request #779
Opened 2021-12-20 21:11 UTC by amiranagram

Add Socialite provider for Monday:

https://apps.developer.monday.com/docs/oauth

2022-01-26 23:08 UTC, atymic commented on src/Monday/README.md
> +- `birthday`
Maybe worth noting that most of these are not set on the object, but you need to getRaw?

2022-01-26 23:08 UTC, atymic reviewed
Looks good, one comment.

2022-01-27 08:06 UTC, lucasmichot requested changes
One small change required

2022-01-27 08:06 UTC, lucasmichot commented on src/Monday/Provider.php
> +                'headers' => [
Please use `RequestOptions::HEADERS` here

2022-01-27 08:06 UTC, lucasmichot commented on src/Monday/Provider.php
> +                'body' => json_encode([
Same here, `RequestOptions::BODY`

2022-01-27 08:08 UTC, lucasmichot submitted a review, later dismissed
Some small changes required

2022-01-27 08:08 UTC, lucasmichot commented on src/Monday/Provider.php
> +    use ConfigTrait;
Remove this trait import

2022-01-27 08:08 UTC, lucasmichot commented on src/Monday/Provider.php
> +class Provider extends AbstractProvider implements ProviderInterface
No need to implements `ProviderInterface`

2022-01-27 08:23 UTC, amiranagram commented
@lucasmichot updated.

2022-01-27 23:59 UTC, atymic approved these changes

2022-01-28 00:02 UTC, atymic requested changes
@amiranagram looks like the syntax doesn't work for php 7.2.
Just force php 7.3 or higher in the composer json please

2022-01-28 00:07 UTC, amiranagram commented
@atymic can you run it again, I fixed the NOWDOC?

2022-01-28 00:26 UTC, merged

2022-02-08 11:29 UTC, amiranagram commented
Hi @atymic @lucasmichot when can we get this provider as a composer package?