Add Mediawiki Provider
SocialiteProviders/Providers pull request #786
Opened 2022-01-01 08:15 UTC by ovruni

OAuth2 Provider for Mediawiki
https://www.mediawiki.org/wiki/OAuth/For_Developers#OAuth_2

2022-01-26 23:07 UTC, atymic commented on src/Mediawiki/Provider.php
> +            'name'     => Arr::get($user, 'realname', ''),
Can we default to null please

2022-01-26 23:07 UTC, atymic requested changes
Just one comment :)

2022-01-28 03:36 UTC, atymic approved these changes

2022-01-28 08:07 UTC, lucasmichot approved these changes

2022-01-31 01:29 UTC, merged