Add Blackboard
SocialiteProviders/Providers pull request #788
Opened 2022-01-10 16:46 UTC by askmrsinh

Blackboard OAuth Overview: https://docs.blackboard.com/rest-apis/learn/getting-started/3lo
Blackboard Developer API reference: https://developer.blackboard.com/portal/displayApi

2022-01-10 18:13 UTC, askmrsinh commented
@atymic @lucasmichot

2022-01-26 22:59 UTC, atymic requested changes

2022-01-26 22:59 UTC, atymic commented on src/Blackboard/Provider.php
> +        $basic_auth = base64_encode($this->clientId.':'.$this->clientSecret);
Can we use the guzzle basic auth param here?
https://docs.guzzlephp.org/en/stable/request-options.html#auth

2022-01-26 22:59 UTC, atymic commented on src/Blackboard/Provider.php
> +        return "https://{$this->getConfig('subdomain')}.blackboard.com/learn/api/public/v1/oauth2/token";
sprintf here please

2022-01-26 22:59 UTC, atymic commented on src/Blackboard/Provider.php
> +        return "https://{$this->getConfig('subdomain')}.blackboard.com/learn/api/public/v1/oauth2/token";
(and in other spots in the PR)

2022-01-26 23:04 UTC, atymic commented
Also missing entry in the split script (monorepobuilder.yml)

2022-02-01 08:26 UTC, lucasmichot approved these changes
Once @atymic comments have been taken in consideratiion, this will be GTM

2022-02-01 08:26 UTC, lucasmichot commented on src/Blackboard/Provider.php
> +        return json_decode($response->getBody(), true);
```suggestion
        return json_decode((string) $response->getBody(), true);
```

2022-02-15 15:19 UTC, lucasmichot approved these changes
GTM @atymic

2022-02-16 23:48 UTC, atymic approved these changes

2022-02-16 23:48 UTC, merged