Add Toyhou.se provider
SocialiteProviders/Providers pull request #829
Opened 2022-04-12 13:05 UTC by sarahjting

Provider for https://toyhou.se/
Developer documentation: https://toyhou.se/~developer/oauth2

Thank you! :)

2022-04-13 10:04 UTC, atymic commented on src/Toyhouse/Provider.php
> +    protected $scopes = [''];
Don't need this, default is empty

2022-04-13 10:04 UTC, atymic requested changes

2022-04-13 10:04 UTC, atymic commented on src/Toyhouse/composer.json
> +        "php": "^7.2 || ^8.0",
```suggestion
        "php": "^7.4 || ^8.0",
```

2022-04-13 11:23 UTC, sarahjting commented
Thank you for review! Have updated 🙇 

It's an art gallery site, similar to deviantArt but supports trading/selling art collections! It's relatively small, but I didn't see any requirements for what sort of providers you're accepting so thought I'd see if I could get it added hehe

2022-04-13 23:06 UTC, atymic requested changes
One minor but good to go otherwise

2022-04-13 23:06 UTC, atymic commented on src/Toyhouse/README.md
> +```
Can you add the returned fields here? See other providers for example on website.

Thanks :)

2022-04-14 14:46 UTC, sarahjting commented
Added! Thanks again ☺️

2022-04-19 00:48 UTC, atymic approved these changes

2022-04-19 00:48 UTC, merged