Add Instructure provider.
SocialiteProviders/Providers pull request #832
Opened 2022-04-14 21:04 UTC by frankperez87

Provider: https://www.instructure.com/
API Docs: https://canvas.instructure.com/doc/api/file.oauth.html

2022-04-14 22:08 UTC, pochocho commented
This provider would be a great addition

2022-04-16 10:19 UTC, lucasmichot approved these changes
Thanks for the contribution, GTM

2022-04-18 15:27 UTC, mdaoustHL approved these changes
🎉

2022-05-13 04:16 UTC, atymic requested changes

2022-05-13 04:16 UTC, atymic commented on src/Instructure/composer.json
> +        "php": "^7.2 || ^8.0",
```suggestion
        "php": "^7.4 || ^8.0",
```

2022-05-13 04:16 UTC, atymic commented
Looks good to me!

2022-05-13 04:19 UTC, atymic approved these changes

2022-05-13 04:23 UTC, merged