Add alipay provider
SocialiteProviders/Providers pull request #851
Opened 2022-05-21 04:50 UTC by leeqvip

Provider for https://www.alipay.com/
Developer documentation: https://opendocs.alipay.com/open/284/web

Thank you! :)

2022-07-26 03:02 UTC, atymic requested changes

2022-07-26 03:02 UTC, atymic commented on src/Alipay/Provider.php
> +            throw new \InvalidArgumentException('You have error! '.\json_encode($response, JSON_UNESCAPED_UNICODE));
```suggestion
            throw new \InvalidArgumentException('Error getting apipay user details '.\json_encode($response, JSON_UNESCAPED_UNICODE));
```

Can we have a more helpful message here please?

2022-07-26 03:02 UTC, atymic commented on src/Alipay/Provider.php
> +            throw new \InvalidArgumentException('You have error! '.json_encode($response, JSON_UNESCAPED_UNICODE));
Also here

2022-07-26 03:02 UTC, atymic commented on src/Alipay/README.md
> +```
Can wee add the returned user fields please

2022-07-26 03:02 UTC, atymic commented on src/Alipay/composer.json
> +        "ext-json": "*",
need to require openssl extension here.

2022-08-04 06:58 UTC, atymic commented
ping @leeqvip

2022-08-12 08:23 UTC, leeqvip commented on src/Alipay/Provider.php
> +    protected $apiVersion = '1.0';
They may be changed in the constructor. I don't want them to be defined as constants.

2022-08-17 23:37 UTC, atymic commented on src/Alipay/composer.json
> +        "php": "^7.4 || ^8.0",
```suggestion
        "php": "^8.0",
```

2022-08-17 23:38 UTC, atymic commented
@lucasmichot can you give this a review as well please?

2022-09-02 10:11 UTC, atymic commented
ping @leeqvip

2022-09-03 08:42 UTC, lucasmichot requested changes

2022-09-03 08:42 UTC, lucasmichot commented on src/Alipay/Provider.php
> +    protected $apiVersion = '1.0';
This is not the way we override environment related variables

2022-09-03 08:42 UTC, lucasmichot commented on src/Alipay/Provider.php
> +            throw new \InvalidArgumentException('Error getting apipay user details '.\json_encode($response, JSON_UNESCAPED_UNICODE));
Please import `InvalidArgumentException`

2022-09-03 08:42 UTC, lucasmichot commented on src/Alipay/Provider.php
> +    protected function getCodeFields($state = null)
Why not just using most of the parent function?

2022-09-03 08:42 UTC, lucasmichot commented on src/Alipay/Provider.php
> +            throw new \InvalidArgumentException('Error getting apipay access token '.json_encode($response, JSON_UNESCAPED_UNICODE));
Please import

2022-09-03 08:42 UTC, lucasmichot commented on src/Alipay/Provider.php
> +    protected function generateSign($params)
generateSign should contain the logic of `signWithSHA256RSA` and `buildParams`

2022-09-03 08:42 UTC, lucasmichot commented on src/Alipay/Provider.php
> +        foreach ($params as $k => $v) {
No need to reinvent `http_build_query` here

2022-09-03 08:42 UTC, lucasmichot commented on src/Alipay/README.md
> +  "sandbox" => env('ALIPAY_SANDBOX') == 'true'
```suggestion
  'sandbox' => (bool) env('ALIPAY_SANDBOX', false),
```

2022-09-03 08:42 UTC, lucasmichot commented on src/Alipay/composer.json
> +        "socialiteproviders/manager": "~4.0"
```suggestion
        "socialiteproviders/manager": "^4.2"
```

2022-10-01 01:44 UTC, atymic commented
cc @leeqvip

2022-10-19 22:44 UTC, atymic commented
cc @leeqvip

2022-10-21 23:40 UTC, atymic commented
Closing due to inactivity

2022-10-21 23:40 UTC, closed without merging