Add FusionAuth provider
SocialiteProviders/Providers pull request #877
Opened 2022-08-04 15:14 UTC by danilopolani

This PR adds a provider for [FusionAuth](https://fusionauth.io/).  

Docs: https://fusionauth.io/docs/v1/tech/oauth/endpoints

PS: I didn't add any "Add base_url to your .env" disclaimer like Auth0 because FusionAuth could be both self-hosted (99% of the times) or cloud, so it could be a bit misleading the example in that paragraph (?)

2022-08-04 22:36 UTC, atymic requested changes
Looks good, just some minor changes :)

2022-08-04 22:36 UTC, atymic commented on src/FusionAuth/Provider.php
> +        return $this->getConfig('base_url').'/oauth2';
Potentially worth throwing an exception here if `base_url` is null? Otherwise will get a confusing string concat error.

2022-08-04 22:36 UTC, atymic commented on src/FusionAuth/Provider.php
> +    /**
No need for this comment

2022-08-04 22:36 UTC, atymic commented on src/FusionAuth/README.md
> +  'base_url' => env('FUSIONAUTH_BASE_URL'),
Maybe add a comment here to clarify?
```suggestion
  'base_url' => env('FUSIONAUTH_BASE_URL'), // Base URL of your cloud instance or self hosted instance
```

2022-08-04 22:36 UTC, atymic commented on src/FusionAuth/README.md
> +```
Can you add the returned user fields here? see other providers for examples

2022-08-04 22:36 UTC, atymic commented on src/FusionAuth/composer.json
> +        "php": "^7.2",
```suggestion
        "php": "^8.0",
```

2022-08-04 22:36 UTC, atymic commented on src/FusionAuth/composer.json
> +    }],
Add keywords 

```
"keywords": [
        "fusionauth",
        "laravel",
        "oauth",
        "provider",
        "socialite"
    ],
```

2022-08-04 22:36 UTC, atymic commented on src/FusionAuth/composer.json
> +    }],
Add support

```
"support": {
        "issues": "https://github.com/socialiteproviders/providers/issues",
        "source": "https://github.com/socialiteproviders/providers",
        "docs": "https://socialiteproviders.com/fusionauth"
    }
```

2022-08-05 07:18 UTC, lucasmichot commented
Thanks for this PR @danilopolani 
Isn't `tenantId` required for the authorization
cf. https://fusionauth.io/docs/v1/tech/oauth/endpoints

2022-08-05 07:27 UTC, danilopolani commented
> Thanks for this PR @danilopolani Isn't `tenantId` required for the authorization cf. https://fusionauth.io/docs/v1/tech/oauth/endpoints

Sorry guys I was sleeping, it's early morning here. I've tried this PR it without tenant id and it works fine, I see that they added that param in v1.8.0, but usually FusionAuth automatically finds the TenantId from the ClientId.

I don't know actually what version I was working on when testing this, I'm gonna do some other test in the next hour and keep you updated. Thank you for taking care of the changes!

2022-08-05 08:08 UTC, danilopolani commented
> Thanks for this PR @danilopolani Isn't `tenantId` required for the authorization cf. [fusionauth.io/docs/v1/tech/oauth/endpoints](https://fusionauth.io/docs/v1/tech/oauth/endpoints)

Added support for `tenantId` in the latest commit, sorry for that. I didn't add a throw when it's missing (like what we do for base url) because prior to v1.8.0 it's not a required field.

Gonna work on other fixes later on, thank you guys!

2022-08-05 08:14 UTC, lucasmichot approved these changes
Thanks for the PR @danilopolani 
GTM @atymic 🚀

2022-08-05 08:57 UTC, atymic approved these changes

2022-08-06 09:12 UTC, merged

2022-08-06 09:29 UTC, atymic commented
https://github.com/SocialiteProviders/FusionAuth/releases/tag/5.0.0 
Please PR to website repo :)

2022-08-06 09:30 UTC, danilopolani commented
> https://github.com/SocialiteProviders/FusionAuth/releases/tag/5.0.0 Please PR to website repo :)

Sure thing, thank you! Sending a PR today