update Zalo Login to V4
SocialiteProviders/Providers pull request #924
Opened 2022-10-12 05:40 UTC by binhuq

Zalo v3 had already deprecated https://developers.zalo.me/docs/api/developer-notification/thong-bao-ngung-ho-tro-hoan-toan-dich-vu-zalo-login-v3-post-6905?campaign=DEVELOPER_BANNER_CAMPAIGN. Update to v4 so zalo provider can working again.

This is my first pull request. Please give feedback if have some problems.

Sorry for my bad English, English is not my first language,

2022-10-19 22:39 UTC, atymic requested changes

2022-10-19 22:39 UTC, atymic commented on src/Zalo/Provider.php
> +     */
No need for this comment

2022-10-19 22:39 UTC, atymic commented on src/Zalo/Provider.php
> +        return json_decode($response->getBody(), true);
String cast here please

2022-10-19 22:39 UTC, atymic commented on src/Zalo/Provider.php
> +            'Content-Type' => 'application/x-www-form-urlencoded',
No need to set this header when using the form params request option

2022-10-19 22:39 UTC, atymic commented on src/Zalo/Provider.php
> +            'secret_key'   => $this->clientSecret,
As this is the only header can you just set it in the get access token response method?

2022-10-19 22:39 UTC, atymic commented on src/Zalo/Provider.php
> +        $response = $this->getHttpClient()->get('graph.zalo.me/v2.0/me', [
```suggestion
        $response = $this->getHttpClient()->get('https://graph.zalo.me/v2.0/me', [
```

2022-10-19 22:39 UTC, atymic commented on src/Zalo/Provider.php
> -        return json_decode((string) $response->getBody(), true);
Leave string cast please

2022-10-19 22:40 UTC, atymic commented
Do you have a link to english docs? I cant get translate to work on the viet ones.

2022-10-21 01:38 UTC, binhuq commented
> Do you have a link to english docs? I cant get translate to work on the viet ones.

Here is english doc. If you don't see english please scroll to bottom and chose English
https://developers.zalo.me/docs/api/social-api-4

2022-10-21 22:16 UTC, atymic approved these changes

2022-10-21 23:05 UTC, merged