[FusionAuth] Changing required properties and better handling API responses
SocialiteProviders/Providers pull request #979
Opened 2023-02-20 20:57 UTC by vcampitelli

Minor changes to the FusionAuth provider:

- :alien: Checking for either `name` or `given_name`/`family_name` attributes when building `User` object (the API may return both)
- :necktie: Making `tenant_id` optional (you can leave it blank if you only have one)
- :pencil2: Fixing typo with the `::class` constant in the README file (it was missing one `:`)

2023-02-21 22:37 UTC, atymic approved these changes

2023-02-21 22:37 UTC, atymic commented on src/FusionAuth/Provider.php
> +        if (!empty($user['name'])) {
```suggestion
        $user['name'] ?? trim($user['given_name'] ?? '' . ' ' . $user['family_name'] ?? '')
```

2023-03-06 23:30 UTC, atymic commented
cc @vcampitelli

2023-03-21 08:17 UTC, atymic requested changes

2023-03-21 08:17 UTC, atymic commented on src/FusionAuth/Provider.php
> +        $user['name'] ?? trim($user['given_name'] ?? '' . ' ' . $user['family_name'] ?? '')
Sorry i mean change the whole statement here to the oneliner i suggested

2023-04-10 05:51 UTC, atymic commented
@vcampitelli

2023-04-10 13:58 UTC, vcampitelli commented
Yes, sorry. That makes more sense :smile: Pushed again. Thanks.

2023-04-29 00:35 UTC, atymic approved these changes

2023-04-29 00:35 UTC, merged